version: "3.7"

services:
    api:
       build: ./restapi
       ports:
         - "${API_PORT:-8080}:8080"
       environment:
         - TRIPLESTORE_CACHE_URL
         - TRIPLESTORE_CACHE_PORT
         - GEOM_DATA_SVC_ENDPOINT
       command: tail -f /dev/null
