version: "3.7"

services:
    api:
       build: ./restapi
       ports:
         - "${API_PORT:-8080}:8080"
       environment:
         - TRIPLESTORE_CACHE_URL
         - TRIPLESTORE_CACHE_PORT
         - GEOM_DATA_SVC_ENDPOINT

    explorerapp:
       build: ./explorer_app
       ports:
         - "${EXPLORER_APP_PORT:-3002}:3002"
